### ISSUE TITLE
快速切换报空指针异常

### ISSUE THREAD

**Issue by coding404** [misakuo/3dTagCloudAndroid#17]
将SIMPLE TEXT TAG和CUSTOM VIEW TAG多次切换后程序奔溃，日志显示空指针异常
` FATAL EXCEPTION: main
                                                                    Process: com.moxun.tagcloud, PID: 20838
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundColor(int)' on a null object reference
                                                                        at com.moxun.tagcloud.ViewTagsAdapter.onThemeColorChanged(ViewTagsAdapter.java:38)
                                                                        at com.moxun.tagcloudlib.view.TagCloudView.onLayout(TagCloudView.java:282)
                                                                        at android.view.View.layout(View.java:15697)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                        at android.view.View.layout(View.java:15697)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5050)`
原因是ViewTagsAdapter中onThemeColorChanged方法未做判空过滤。

**Comment by misakuo** [comment]
欢迎提交PR修复
